public with sharing class SimpleConditional1 
{
    public static Boolean IsEqual(Integer one, Integer other)
    {
        // change this method to return true when
        // one is equal to other and false when
        // one is not equal to other

        Boolean equalCheck = false;

        if (one == other){
            equalCheck = true;
        }

        //nothing else needed
        return equalCheck;
    }

    public static Boolean IsPositive(Integer num)
    {
        // change this method to return true when
        // the number is greater than zero and false otherwise
        return null;
    }

    public static Boolean IsEven(Integer num)
    {
        // change this method to return true when
        // the number is even and false when the
        // the number is odd
        return null;
    }

    public static Integer GetLargest(Integer first, Integer second, Integer third, Integer fourth)
    {
        // change this method to return a the largest of
        // the four numbers
        return null;
    }

    public static Integer Compare(Integer one, Integer other)
    {
        // change this method to return -1 when one is less than
        // other, +1 when one is greater than other, 0 if one
        // is the same as other
        return null;
    }
    
}
